import { schema, t } from "@colyseus/schema";

export const PlayerSchema = schema({
  sessionId: t.string(),
  seatIndex: t.number(),
  name: t.string(),
  connected: t.boolean(),
  ready: t.boolean(),
  life: t.number(),
  handCount: t.number(),
  deckCount: t.number(),
  initiative: t.number(),
  mana: t.number(),
  sangue: t.number(),
  ossos: t.number(),
  sucata: t.number(),
  manaUsed: t.number(),
  sangueUsed: t.number(),
  ossosUsed: t.number(),
  sucataUsed: t.number(),
  resourcePlaced: t.boolean(),
  resourceRemoved: t.boolean(),
  troopsPlayed: t.number(),
  constructionsPlayed: t.number(),
  spellsUsed: t.number(),
  itemsUsed: t.number(),
  terrainPlayed: t.boolean(),
  hasTakenTurn: t.boolean(),
  initialHandDrawn: t.boolean(),
  blockedResource: t.string(),
  blockedTurns: t.number(),
  evolutionsUsed: t.number(),
});

export const PublicCardSchema = schema({
  instanceId: t.string(),
  definitionId: t.string(),
  name: t.string(),
  category: t.string(),
  owner: t.number(),
  lane: t.number(),
  position: t.number(),
  life: t.number(),
  maxLife: t.number(),
  moved: t.boolean(),
  attacked: t.boolean(),
  defendingCastle: t.boolean(),
  turnsInPlay: t.number(),
  condition: t.string(),
  conditionTurns: t.number(),
  conditionPower: t.number(),
  intelligence: t.number(),
  equipmentJson: t.string(),
  abilityStateJson: t.string(),
});

export const KarthaRoomState = schema({
  players: t.map(PlayerSchema),
  cards: t.map(PublicCardSchema),
  phase: t.string(),
  currentPlayer: t.number(),
  initiativeWinner: t.number(),
  winner: t.number(),
  revision: t.number(),
  seed: t.number(),
  turnNumber: t.number(),
  terrainDefinitionId: t.string(),
  discardCount0: t.number(),
  discardCount1: t.number(),
  lastAction: t.string(),
});
