depth = -100;
nome_construcao = "Torre";
vida = 5;
vida_maxima = 5;
dono = "jogador";
lane_atual = 0;
slot_atual = noone;
habilidade_usada_este_turno = false;
tem_habilidade_construcao = false; // marca se essa construção tem poder ativo
entrada_visual_timer = 24;
entrada_visual_duracao = 24;
